url:
  event: data/chiba_festival.json
  city: data/12chiba.json
  announcement: data/announcement.json
  weather: https://s3-ap-northeast-1.amazonaws.com/staging.weather.api.code4chiba.org/weather.json
protocol: JSON
