url:
  event: data/chiba_festival.json
  city: data/12chiba.json
  announcement: data/announcement.json
  weather_cache: data/weather.json
  weather:
    url: http://api.yumake.jp/1.0/forecastPrefWeek.php
    cityCode: 12
protocol: JSON
