url:
  event: data/chiba_festival.json
  city: data/12chiba.json
  announcement: data/announcement.json
  weather: https://api.staging.code4chiba.org/v1/weathers
protocol: JSON
config_name: 'default.yml'
