kind: Service
apiVersion: v1
metadata:
  name: server-dispatcher
  namespace: cfc-festival-staging
spec:
  selector:
    app: server
    environment: staging
  ports:
    -
      protocol: "TCP"
      port: 9000
