kind: Service
apiVersion: v1
metadata:
  name: server-dispatcher
  namespace: cfc-festival
spec:
  selector:
    app: server
    environment: production
  ports:
    -
      protocol: "TCP"
      port: 9000
